[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
